// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calcDissimilarityMatrixCpp
NumericMatrix calcDissimilarityMatrixCpp(IntegerMatrix zmat);
RcppExport SEXP _THREAD_calcDissimilarityMatrixCpp(SEXP zmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type zmat(zmatSEXP);
    rcpp_result_gen = Rcpp::wrap(calcDissimilarityMatrixCpp(zmat));
    return rcpp_result_gen;
END_RCPP
}
// update_clusters_cpp_hetero
List update_clusters_cpp_hetero(NumericMatrix x_train, NumericVector y_train, NumericVector d0, NumericVector d1, NumericVector d2, IntegerVector z, NumericMatrix gamma, double alpha, int m, double prior_sd);
RcppExport SEXP _THREAD_update_clusters_cpp_hetero(SEXP x_trainSEXP, SEXP y_trainSEXP, SEXP d0SEXP, SEXP d1SEXP, SEXP d2SEXP, SEXP zSEXP, SEXP gammaSEXP, SEXP alphaSEXP, SEXP mSEXP, SEXP prior_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_train(x_trainSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_train(y_trainSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type prior_sd(prior_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(update_clusters_cpp_hetero(x_train, y_train, d0, d1, d2, z, gamma, alpha, m, prior_sd));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_THREAD_calcDissimilarityMatrixCpp", (DL_FUNC) &_THREAD_calcDissimilarityMatrixCpp, 1},
    {"_THREAD_update_clusters_cpp_hetero", (DL_FUNC) &_THREAD_update_clusters_cpp_hetero, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_THREAD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
