# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Posterior dissimilarity matrix from MCMC label draws
#'
#' For every pair of genes, returns one minus the fraction of MCMC draws in
#' which the two genes share a cluster label (i.e. one minus their posterior
#' co-assignment probability). The diagonal is zero.
#'
#' @param zmat An integer matrix of label draws with one row per retained draw
#'   and one column per gene.
#' @return A symmetric numeric matrix of dissimilarities (genes by genes).
#' @keywords internal
calcDissimilarityMatrixCpp <- function(zmat) {
    .Call(`_THREAD_calcDissimilarityMatrixCpp`, zmat)
}

update_clusters_cpp_hetero <- function(x_train, y_train, d0, d1, d2, z, gamma, alpha, m, prior_sd) {
    .Call(`_THREAD_update_clusters_cpp_hetero`, x_train, y_train, d0, d1, d2, z, gamma, alpha, m, prior_sd)
}

